---
# VersionMark Configuration File
# This file defines which tools to capture and how to extract their version information.

tools:
  # .NET SDK
  dotnet:
    command: dotnet --version
    regex: '(?<version>\d+\.\d+\.\d+)'

  # Git
  git:
    command: git --version
    regex: 'git version (?<version>\d+\.\d+\.\d+)'

  # Node.js
  node:
    command: node --version
    regex: 'v(?<version>\d+\.\d+\.\d+)'

  # npm
  npm:
    command: npm --version
    regex: '(?<version>\d+\.\d+\.\d+)'

  # SonarScanner for .NET (from dotnet tool list)
  dotnet-sonarscanner:
    command: dotnet tool list
    regex: 'dotnet-sonarscanner\s+(?<version>\d+\.\d+\.\d+)'

  # Pandoc (DemaConsulting.PandocTool from dotnet tool list)
  pandoc:
    command: dotnet tool list
    regex: 'demaconsulting\.pandoctool\s+(?<version>\d+\.\d+\.\d+)'

  # WeasyPrint (DemaConsulting.WeasyPrintTool from dotnet tool list)
  weasyprint:
    command: dotnet tool list
    regex: 'demaconsulting\.weasyprinttool\s+(?<version>\d+\.\d+\.\d+)'

  # SarifMark (DemaConsulting.SarifMark from dotnet tool list)
  sarifmark:
    command: dotnet tool list
    regex: 'demaconsulting\.sarifmark\s+(?<version>\d+\.\d+\.\d+)'

  # SonarMark (DemaConsulting.SonarMark from dotnet tool list)
  sonarmark:
    command: dotnet tool list
    regex: 'demaconsulting\.sonarmark\s+(?<version>\d+\.\d+\.\d+)'

  # ReqStream (DemaConsulting.ReqStream from dotnet tool list)
  reqstream:
    command: dotnet tool list
    regex: 'demaconsulting\.reqstream\s+(?<version>\d+\.\d+\.\d+)'

  # BuildMark (DemaConsulting.BuildMark from dotnet tool list)
  buildmark:
    command: dotnet tool list
    regex: 'demaconsulting\.buildmark\s+(?<version>\d+\.\d+\.\d+)'
