---
# VersionMark Configuration File
# This file defines which tools to capture and how to extract their version information.

tools:
  # .NET SDK
  dotnet:
    command: dotnet --version
    regex: '(?P<version>\d+\.\d+\.\d+)'

  # Git
  git:
    command: git --version
    regex: 'git version (?P<version>\d+\.\d+\.\d+)'

  # Node.js
  node:
    command: node --version
    regex: 'v(?P<version>\d+\.\d+\.\d+)'

  # npm
  npm:
    command: npm --version
    regex: '(?P<version>\d+\.\d+\.\d+)'
