---
# yamllint configuration for Template DotNet Tool
# This configuration defines the rules for YAML file linting

extends: default

rules:
  # Allow 'on:' in GitHub Actions workflows (not a boolean value)
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
    check-keys: true

  # Allow longer lines for URLs and complex expressions
  line-length:
    max: 120
    level: error

  # Ensure proper indentation
  indentation:
    spaces: 2
    indent-sequences: true

  # Ensure proper comment formatting
  comments:
    min-spaces-from-content: 2
