---
# VersionMark Requirements
#
# This file defines the requirements for the VersionMark tool.
# Requirements are verified through tests and documented in docs/requirements/ and docs/tracematrix/.

includes:
  - docs/reqstream/command-line.yaml
  - docs/reqstream/capture.yaml
  - docs/reqstream/publish.yaml
  - docs/reqstream/configuration.yaml
  - docs/reqstream/formatter.yaml
  - docs/reqstream/runtime.yaml
  - docs/reqstream/ots-software.yaml
