# Requirements Testing Strategy
#
# This project uses three categories of tests to verify requirements:
#
# 1. Unit Tests - Run locally via "dotnet test"
# 2. Self-Validation Tests - Run locally via "--validate"
# 3. Platform Tests - Run via CI/CD across OS/runtime matrix
#
# NOTE: Running "reqstream --enforce" with only local test results (unit tests
# and local self-validation) is expected to show some unsatisfied requirements.
# Platform-specific requirements require test results from CI/CD runs across
# the full OS and runtime matrix.
#
---
sections:
  - title: VersionMark Requirements
    sections:
      - title: Command-Line Interface
        requirements:
          - id: CMD-001
            title: The tool shall implement a Context class for command-line argument handling.
            justification: |
              Provides a standardized approach to command-line argument parsing and output
              handling across all DEMA Consulting DotNet Tools.
            tags:
              - cli
            tests:
              - Context_Create_NoArguments_ReturnsDefaultContext
              - Context_Create_VersionFlag_SetsVersionTrue
              - Context_Create_HelpFlag_SetsHelpTrue
              - Context_Create_SilentFlag_SetsSilentTrue
              - Context_Create_ValidateFlag_SetsValidateTrue
              - Context_Create_ResultsFlag_SetsResultsFile
              - Context_Create_LogFlag_OpensLogFile

          - id: CMD-002
            title: The tool shall support -v and --version flags to display version information.
            justification: |
              Users need to quickly identify the version of the tool they are using for
              troubleshooting and compatibility verification.
            tags:
              - cli
            tests:
              - Context_Create_VersionFlag_SetsVersionTrue
              - Context_Create_ShortVersionFlag_SetsVersionTrue
              - Program_Run_WithVersionFlag_DisplaysVersionOnly
              - IntegrationTest_VersionFlag_OutputsVersion

          - id: CMD-003
            title: The tool shall support -?, -h, and --help flags to display usage information.
            justification: |
              Users need access to command-line usage documentation without requiring
              external resources.
            tags:
              - cli
            tests:
              - Context_Create_HelpFlag_SetsHelpTrue
              - Context_Create_ShortHelpFlag_H_SetsHelpTrue
              - Context_Create_ShortHelpFlag_Question_SetsHelpTrue
              - Program_Run_WithHelpFlag_DisplaysUsageInformation
              - IntegrationTest_HelpFlag_OutputsUsageInformation

          - id: CMD-004
            title: The tool shall support --silent flag to suppress console output.
            justification: |
              Enables automated scripts and CI/CD pipelines to run the tool without
              cluttering output logs.
            tags:
              - cli
            tests:
              - Context_Create_SilentFlag_SetsSilentTrue
              - Context_WriteLine_Silent_DoesNotWriteToConsole
              - IntegrationTest_SilentFlag_SuppressesOutput

          - id: CMD-005
            title: The tool shall support --validate flag to run self-validation tests.
            justification: |
              Provides a built-in mechanism to verify the tool is functioning correctly
              in the deployment environment.
            tags:
              - cli
            tests:
              - Context_Create_ValidateFlag_SetsValidateTrue
              - Program_Run_WithValidateFlag_RunsValidation
              - IntegrationTest_ValidateFlag_RunsValidation

          - id: CMD-006
            title: The tool shall support --results flag to write validation results in TRX or JUnit format.
            justification: |
              Enables integration with CI/CD systems that expect standard test result formats.
            tags:
              - cli
            tests:
              - Context_Create_ResultsFlag_SetsResultsFile
              - IntegrationTest_ValidateWithResults_GeneratesTrxFile

          - id: CMD-007
            title: The tool shall support --log flag to write output to a log file.
            justification: |
              Provides persistent logging for debugging and audit trails.
            tags:
              - cli
            tests:
              - Context_Create_LogFlag_OpensLogFile
              - IntegrationTest_LogFlag_WritesOutputToFile

      - title: Platform Support
        requirements:
          - id: PLT-001
            title: The tool shall build and run on Windows platforms.
            justification: |
              DEMA Consulting tools must support Windows as a major development platform.
            tags:
              - platform
            tests:
              # Tests link to "windows" to ensure results come from Windows platform
              - "windows@VersionMark_VersionDisplay"
              - "windows@VersionMark_HelpDisplay"

          - id: PLT-002
            title: The tool shall build and run on Linux platforms.
            justification: |
              DEMA Consulting tools must support Linux for CI/CD and containerized environments.
            tags:
              - platform
            tests:
              # Tests link to "ubuntu" to ensure results come from Linux platform
              - "ubuntu@VersionMark_VersionDisplay"
              - "ubuntu@VersionMark_HelpDisplay"

          - id: PLT-003
            title: The tool shall support .NET 8 runtime.
            justification: |
              .NET 8 is an LTS release providing long-term stability for enterprise users.
            tags:
              - platform
            tests:
              - "dotnet8.x@VersionMark_VersionDisplay"
              - "dotnet8.x@VersionMark_HelpDisplay"

          - id: PLT-004
            title: The tool shall support .NET 9 runtime.
            justification: |
              .NET 9 support enables users to leverage the latest .NET features.
            tags:
              - platform
            tests:
              - "dotnet9.x@VersionMark_VersionDisplay"
              - "dotnet9.x@VersionMark_HelpDisplay"

          - id: PLT-005
            title: The tool shall support .NET 10 runtime.
            justification: |
              .NET 10 support ensures the tool remains compatible with the latest .NET ecosystem.
            tags:
              - platform
            tests:
              - "dotnet10.x@VersionMark_VersionDisplay"
              - "dotnet10.x@VersionMark_HelpDisplay"

      - title: Configuration File
        requirements:
          - id: CFG-001
            title: The tool shall read configuration from a .versionmark.yaml file.
            justification: |
              Provides a standardized configuration format for defining tools and their
              version capture commands.
            tags:
              - configuration
            tests:
              - VersionMarkConfig_ReadFromFile_ValidFile_ReturnsConfig
              - VersionMarkConfig_ReadFromFile_WithAllOsOverrides_ReturnsConfig

          - id: CFG-002
            title: The tool shall support tool definitions with command and regex properties.
            justification: |
              Enables users to specify how to execute and parse version information for
              each tool.
            tags:
              - configuration
            tests:
              - VersionMarkConfig_ReadFromFile_ValidFile_ReturnsConfig
              - ToolConfig_GetEffectiveCommand_NoOverride_ReturnsDefaultCommand
              - ToolConfig_GetEffectiveRegex_NoOverride_ReturnsDefaultRegex

          - id: CFG-003
            title: The tool shall support OS-specific command overrides using -win, -linux, and -macos suffixes.
            justification: |
              Different operating systems may require different commands or command
              variations to capture tool versions.
            tags:
              - configuration
            tests:
              - VersionMarkConfig_ReadFromFile_WithAllOsOverrides_ReturnsConfig
              - ToolConfig_GetEffectiveCommand_WindowsOverride_ReturnsWindowsCommand
              - ToolConfig_GetEffectiveCommand_LinuxOverride_ReturnsLinuxCommand
              - ToolConfig_GetEffectiveCommand_MacOsOverride_ReturnsMacOsCommand

          - id: CFG-004
            title: The tool shall support OS-specific regex overrides using -win, -linux, and -macos suffixes.
            justification: |
              Different operating systems may produce different output formats requiring
              different regular expressions for version extraction.
            tags:
              - configuration
            tests:
              - VersionMarkConfig_ReadFromFile_WithAllOsOverrides_ReturnsConfig
              - ToolConfig_GetEffectiveRegex_WindowsOverride_ReturnsWindowsRegex
              - ToolConfig_GetEffectiveRegex_LinuxOverride_ReturnsLinuxRegex
              - ToolConfig_GetEffectiveRegex_MacOsOverride_ReturnsMacOsRegex

          - id: CFG-005
            title: The tool shall validate that configuration files contain at least one tool definition.
            justification: |
              Prevents misconfiguration by ensuring the configuration file has actionable
              content.
            tags:
              - configuration
            tests:
              - VersionMarkConfig_ReadFromFile_NoTools_ThrowsArgumentException

          - id: CFG-006
            title: The tool shall report errors when configuration files cannot be read or parsed.
            justification: |
              Provides clear feedback to users when configuration files are missing,
              inaccessible, or malformed.
            tags:
              - configuration
            tests:
              - VersionMarkConfig_ReadFromFile_NonExistentFile_ThrowsArgumentException
              - VersionMarkConfig_ReadFromFile_InvalidYaml_ThrowsArgumentException

      - title: Capture Command
        requirements:
          - id: CAP-001
            title: The tool shall support --capture flag to enable capture mode.
            justification: |
              Provides a way to capture tool versions from the current environment for
              version tracking and CI/CD integration.
            tags:
              - capture
            tests:
              - Program_Run_WithCaptureCommand_CapturesToolVersions
              - IntegrationTest_CaptureCommand_CapturesToolVersions

          - id: CAP-002
            title: The tool shall require --job-id parameter when capture mode is enabled.
            justification: |
              The job ID uniquely identifies the capture session and is used in the
              default output filename, ensuring traceability of captured versions.
            tags:
              - capture
            tests:
              - Program_Run_WithCaptureCommandWithoutJobId_ReturnsError
              - IntegrationTest_CaptureCommandWithoutJobId_ReturnsError

          - id: CAP-003
            title: The tool shall support --output parameter to specify the JSON output file path.
            justification: |
              Allows users to control where captured version information is saved,
              enabling integration with existing workflows and file structures.
            tags:
              - capture
            tests:
              - Program_Run_WithCaptureCommand_CapturesToolVersions
              - IntegrationTest_CaptureCommand_CapturesToolVersions

          - id: CAP-004
            title: The tool shall default output filename to versionmark-<job-id>.json when --output is not specified.
            justification: |
              Provides a predictable default naming convention that includes the job ID,
              making it easy to identify and organize capture files.
            tags:
              - capture
            tests:
              - IntegrationTest_CaptureCommandWithDefaultOutput_UsesDefaultFilename

          - id: CAP-005
            title: The tool shall accept an optional list of tool names after -- separator in capture mode.
            justification: |
              Allows users to capture versions for specific tools rather than all configured
              tools, improving performance and reducing unnecessary captures.
            tags:
              - capture
            tests:
              - Program_Run_WithCaptureCommand_CapturesToolVersions
              - IntegrationTest_CaptureCommand_CapturesToolVersions

          - id: CAP-006
            title: The tool shall capture all tools defined in configuration when no tool names are specified.
            justification: |
              Provides a convenient default behavior where all configured tools are captured,
              suitable for comprehensive version tracking scenarios.
            tags:
              - capture
            tests:
              - IntegrationTest_CaptureCommandWithDefaultOutput_UsesDefaultFilename

          - id: CAP-007
            title: The tool shall read .versionmark.yaml from the current directory in capture mode.
            justification: |
              Uses the standard configuration file location to determine which tools to
              capture and how to capture them.
            tags:
              - capture
            tests:
              - Program_Run_WithCaptureCommand_CapturesToolVersions
              - IntegrationTest_CaptureCommand_CapturesToolVersions
              - Program_Run_WithCaptureCommandWithMissingConfig_ReturnsError
              - IntegrationTest_CaptureCommandWithMissingConfig_ReturnsError

          - id: CAP-008
            title: The tool shall execute configured commands and extract version information using regex patterns.
            justification: |
              Implements the core capture functionality by running tool commands and parsing
              their output to extract version numbers.
            tags:
              - capture
            tests:
              - Program_Run_WithCaptureCommand_CapturesToolVersions
              - IntegrationTest_CaptureCommand_CapturesToolVersions

          - id: CAP-009
            title: The tool shall save captured version information to a JSON file with job ID and version mappings.
            justification: |
              Stores captured versions in a structured format that can be easily consumed
              by other tools and systems.
            tags:
              - capture
            tests:
              - Program_Run_WithCaptureCommand_CapturesToolVersions
              - IntegrationTest_CaptureCommand_CapturesToolVersions
              - IntegrationTest_CaptureCommandWithDefaultOutput_UsesDefaultFilename

          - id: CAP-010
            title: The tool shall display captured tool names and versions to the user.
            justification: |
              Provides immediate feedback to users about what versions were captured,
              enabling verification of the capture operation.
            tags:
              - capture
            tests:
              - Program_Run_WithCaptureCommand_CapturesToolVersions
              - IntegrationTest_CaptureCommand_CapturesToolVersions

          - id: CAP-011
            title: The tool shall report errors when .versionmark.yaml cannot be found or read in capture mode.
            justification: |
              Provides clear error messages to users when the configuration file is missing
              or inaccessible, preventing silent failures.
            tags:
              - capture
            tests:
              - Program_Run_WithCaptureCommandWithMissingConfig_ReturnsError
              - IntegrationTest_CaptureCommandWithMissingConfig_ReturnsError
