---
name: 🐛 Bug Report
description: Report a bug or issue with the TemplateDotNetTool
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below to help us understand and
        fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Run TemplateDotNetTool with command '...'
        2. Provide input file '...'
        3. Observe error...
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: Describe what actually happens...
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: If applicable, provide a minimal code sample that reproduces the issue
      placeholder: |
        ```csharp
        // Your code here
        ```
      render: csharp

  - type: input
    id: version
    attributes:
      label: Tool Version
      description: What version of the TemplateDotNetTool are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: dropdown
    id: dotnet-version
    attributes:
      label: .NET Version
      description: What version of .NET are you using?
      options:
        - ".NET 8"
        - ".NET 9"
        - ".NET 10"
        - Other (please specify in additional context)
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: e.g., Windows 11, Ubuntu 22.04, macOS 14.0

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, such as error messages, stack traces, or screenshots
      placeholder: Any additional information...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a clear description of the problem
          required: true
        - label: I have included steps to reproduce the issue
          required: true
