---
name: ✨ Feature Request
description: Suggest a new feature or enhancement for the TemplateDotNetTool
title: "[Feature]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the sections below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when... / I need to be able to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: A clear and concise description of any alternative solutions or features

  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: If applicable, provide examples of how this feature would be used
      placeholder: |
        ```csharp
        // Example usage
        templatetool --input report.json --output report.md --feature-flag
        ```
      render: csharp

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: Explain why this enhancement would be useful to TemplateDotNetTool users
      placeholder: This would be useful because...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Blocking my use case
    validations:
      required: true

  - type: dropdown
    id: willingness
    attributes:
      label: Willingness to Contribute
      description: Would you be willing to contribute this feature?
      options:
        - "Yes, I can submit a pull request"
        - "Yes, with guidance from maintainers"
        - "No, but I can help test it"
        - "No, I'm just suggesting"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or links about the feature request here
      placeholder: Any additional information...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a clear description of the feature
          required: true
        - label: I have explained why this feature would be useful
          required: true
